#!/usr/bin/env node
// scripts/inject-env.js
// Reads FIREBASE_* env vars and writes public/env.js so the browser can
// access them without exposing a .env file in the repo.
// Called automatically by the Netlify build command (see netlify.toml).

const fs   = require("fs");
const path = require("path");

require("dotenv").config();

const keys = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
];

const values = {};
keys.forEach(k => { values[k] = process.env[k] || ""; });

const content = `// Auto-generated by scripts/inject-env.js — do not edit manually.
window.__ENV__ = ${JSON.stringify(values, null, 2)};
`;

const outDir = path.join(__dirname, "..", "public");
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

fs.writeFileSync(path.join(outDir, "env.js"), content, "utf8");
console.log("[inject-env] Wrote public/env.js with keys:", keys.join(", "));
